"""pablo base de datos test

Revision ID: 2ce95fc86d60
Revises: fe3fcfd2a86b
Create Date: 2024-04-07 01:25:25.767802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce95fc86d60'
down_revision: Union[str, None] = 'fe3fcfd2a86b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
