"""nueva base de datos postgres1

Revision ID: 77f7f6b6bce2
Revises: 6792d08bda43
Create Date: 2024-04-07 17:28:54.048579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77f7f6b6bce2'
down_revision: Union[str, None] = '6792d08bda43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
