"""nueva base de datos postgres de nuevo

Revision ID: f4b9ee9e17a9
Revises: 77f7f6b6bce2
Create Date: 2024-04-07 17:33:20.088697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4b9ee9e17a9'
down_revision: Union[str, None] = '77f7f6b6bce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
